### ISSUE TITLE
write long has a error in SpStream

### ISSUE THREAD

**Issue by LokerLi** [jintiao/sproto-cs#2]
write long has a error in SpStream line 126

```
public void Write (long n) {
    if (CanWrite (2)) {
        mBuffer[mPosition + 0] = (byte)(n & 0xff);
        mBuffer[mPosition + 1] = (byte)((n >> 8) & 0xff);
        mBuffer[mPosition + 2] = (byte)((n >> 16) & 0xff);
        mBuffer[mPosition + 3] = (byte)((n >> 24) & 0xff);
        mBuffer[mPosition + 3] = (byte)((n >> 32) & 0xff);
        mBuffer[mPosition + 3] = (byte)((n >> 40) & 0xff);
        mBuffer[mPosition + 3] = (byte)((n >> 48) & 0xff);
        mBuffer[mPosition + 3] = (byte)((n >> 56) & 0xff);
    }
    PositionAdd (8);
}
```

fixed to:
    public void Write (long n) {
        if (CanWrite (2)) {
            mBuffer[mPosition + 0] = (byte)(n & 0xff);
            mBuffer[mPosition + 1] = (byte)((n >> 8) & 0xff);
            mBuffer[mPosition + 2] = (byte)((n >> 16) & 0xff);
            mBuffer[mPosition + 3] = (byte)((n >> 24) & 0xff);
            mBuffer[mPosition + 4] = (byte)((n >> 32) & 0xff);
            mBuffer[mPosition + 5] = (byte)((n >> 40) & 0xff);
            mBuffer[mPosition + 6] = (byte)((n >> 48) & 0xff);
            mBuffer[mPosition + 7] = (byte)((n >> 56) & 0xff);
        }
        PositionAdd (8);
    }

**Comment by jintiao** [comment]
fixed. thank you.
