### ISSUE TITLE
发送一定长度的字符串时发现问题

### ISSUE THREAD

**Issue by LokerLi** [jintiao/sproto-cs#3]
xxxx 1 {
    request {
            Type 0 : integer
            Content 1 : string
    }
    response {
    }
}
我定了这样的一个协议，发送给SKYNET，发现当Content为8个汉字时，SKYNET会报错误:./lualib/skynet.lua:537: ./lualib/sproto.lua:143: Invalid unpack stream,  local bin = core.unpack(...)是这个位置

后来测试发现Content每递增8个长度都会报相同的错误，8，16，24，32，40......
现在暂时没有找到具体原因

**Comment by jintiao** [comment]
我简单测试了一下，没有重现出来。
服务器直接跑skynet官方的 ./skynet example/config
客户端用sproto-u3d的Client测试例子。
中文8个字符没有出错。
把proto.lua改成你描述的样子再跑也是没有出错。

**Comment by LokerLi** [comment]
应该是压缩的问题，当压缩的长度为8的倍数是必现，现在我的解决方法是：
在SpPacker.cs中的Pack方法修改当n==10,src_size++, 不知道还有没有其实更好的方法。
 if (n == 10) {
                ff_src_start = src_offset;
                ff_dest_start = pos;
                ff_n = 1;
                src_size++;
            }
请用下面的代码测试：
public class TestRpc {
    private const string server_proto = @"
        .package {
            type 0 : integer
            session 1 : integer
        }
        str 1 {
            request {
                Type 0 : integer
                Content 1 : string
                }
                response {
                }
        }
        ";

```
const string client_proto = @"
    .package {
        type 0 : integer
        session 1 : integer
    }
    ";

private SpRpc server;
private SpRpc client;

public void Run () {
    SpTypeManager server_tm = SpTypeManager.Import (server_proto);

    server = SpRpc.Create (server_tm, "package");

    client = SpRpc.Create (client_proto, "package");
    client.Attach (server_tm);
    Teststr();
    Console.ReadKey();
}
private void Teststr()
{
    Util.Log("client request str");

    SpObject foobar_request = new SpObject();
    foobar_request.Insert("Type", 1);
    foobar_request.Insert("Content", "测试测试测试测试");
    //foobar_request.Insert("Content", "测试测试测试测试1");
    //foobar_request.Insert("Content", "测试测试测试测试测试测试测试测试");
    SpStream req = client.Request("str", foobar_request, 5);

    //Util.Assert(req.Length == 11);
    Util.Log("request foobar size = " + req.Length);

    req.Position = 0;
    SpRpcResult dispatch_result = server.Dispatch(req);
    //Util.Assert(dispatch_result.Data["what"].AsString().Equals("foo"));
    Util.DumpObject(dispatch_result.Arg);
}
```

}

**Comment by jintiao** [comment]
问题确实存在，我会尽快修复这个bug，谢谢

**Comment by jintiao** [comment]
hi, 旧版本对string的pack有些问题，请pull一下最新的代码，希望能修复这个bug。

**Comment by LokerLi** [comment]
刚测试了一下，完美解决了这个问题，赞
